# Generated by Django 6.0.5 on 2026-05-27 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('estrutura', models.CharField(choices=[('ombro', 'Ombro'), ('joelho', 'Joelho'), ('quadril', 'Quadril'), ('coluna', 'Coluna'), ('cotovelo', 'Cotovelo'), ('punho', 'Punho'), ('tornozelo', 'Tornozelo'), ('outros', 'Outros')], max_length=50)),
                ('descricao', models.TextField()),
                ('como_realizar', models.TextField()),
                ('foto', models.ImageField(blank=True, null=True, upload_to='testes/')),
                ('achado_positivo', models.TextField(help_text='O que indica quando positivo')),
                ('achado_negativo', models.TextField(blank=True, help_text='O que indica quando negativo')),
                ('sensibilidade', models.CharField(blank=True, help_text='Ex: 72%', max_length=20)),
                ('especificidade', models.CharField(blank=True, help_text='Ex: 66%', max_length=20)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Teste Especial',
                'verbose_name_plural': 'Testes Especiais',
                'ordering': ['nome'],
            },
        ),
    ]
