# Generated by Django 6.0.5 on 2026-06-18 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patologias', '0003_alter_sintomapatologia_options_and_more'),
        ('testes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teste',
            name='patologias_relacionadas',
            field=models.ManyToManyField(blank=True, related_name='testes', to='patologias.patologia'),
        ),
    ]
