# Generated by Django 6.0.5 on 2026-06-23 23:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testes', '0002_teste_patologias_relacionadas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teste',
            name='patologias_relacionadas',
        ),
    ]
