# Generated by Django 6.0.5 on 2026-07-09 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testes', '0003_remove_teste_patologias_relacionadas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teste',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='fisioapp/testes/'),
        ),
    ]
