# Generated by Django 6.0.5 on 2026-05-29 23:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SimulacaoConsulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, max_length=200)),
                ('nivel', models.CharField(choices=[('facil', 'Fácil - Paciente colaborativo, sintomas claros'), ('medio', 'Médio - Paciente com algumas dificuldades de comunicação'), ('dificil', 'Difícil - Paciente confuso, sintomas vagos, historico complexo')], default='medio', max_length=10)),
                ('patologia_simulada', models.CharField(blank=True, help_text='Patologia que o paciente virtual possui (oculto do profissional)', max_length=200)),
                ('ativa', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('finalizado_em', models.DateTimeField(blank=True, null=True)),
                ('fisioterapeuta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='simulacoes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Simulação de Consulta',
                'verbose_name_plural': 'Simulações de Consulta',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='MensagemSimulacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remetente', models.CharField(choices=[('fisio', 'Fisioterapeuta'), ('paciente', 'Paciente (IA)')], max_length=10)),
                ('conteudo', models.TextField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('simulacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensagens', to='consulta_ia.simulacaoconsulta')),
            ],
            options={
                'ordering': ['criado_em'],
            },
        ),
    ]
