# Generated by Django 6.0.5 on 2026-05-29 22:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('data_nascimento', models.DateField()),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino'), ('O', 'Outro')], max_length=1)),
                ('estado_civil', models.CharField(blank=True, choices=[('solteiro', 'Solteiro(a)'), ('casado', 'Casado(a)'), ('divorciado', 'Divorciado(a)'), ('viuvo', 'Viúvo(a)'), ('uniao_estavel', 'União Estável')], max_length=20)),
                ('profissao', models.CharField(blank=True, max_length=100)),
                ('telefone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('endereco', models.TextField(blank=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='pacientes/')),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('fisioterapeuta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pacientes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Paciente',
                'verbose_name_plural': 'Pacientes',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Anamnese',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('queixa_principal', models.TextField(help_text='Motivo principal da consulta')),
                ('historia_doenca_atual', models.TextField(help_text='Inicio, evolução e caracteristicas da queixa')),
                ('localizacao_dor', models.CharField(blank=True, max_length=200)),
                ('intensidade_dor', models.IntegerField(choices=[(0, '0 — Sem dor'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5 — Dor moderada'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10 — Pior dor possível')], default=0)),
                ('tipo_dor', models.CharField(blank=True, help_text='Ex: queimação, pontada, pressão, etc.', max_length=100)),
                ('dor_irradia', models.BooleanField(default=False)),
                ('irradiacao_descricao', models.CharField(blank=True, max_length=200)),
                ('fatores_piora', models.TextField(blank=True, help_text='O que piora a dor ?')),
                ('fatores_melhora', models.TextField(blank=True, help_text='O que melhora a dor ?')),
                ('antecedentes_pessoais', models.TextField(blank=True, help_text='Doenças, cirurgias, internações anteriores')),
                ('antecedentes_familiares', models.TextField(blank=True)),
                ('medicamentos_em_uso', models.TextField(blank=True)),
                ('alergias', models.TextField(blank=True)),
                ('tratamentos_anteriores', models.TextField(blank=True, help_text='Fisioterapia, médico, etc.')),
                ('atividade_fisica', models.BooleanField(default=False)),
                ('descricao_atividade_fisica', models.CharField(blank=True, max_length=200)),
                ('tabagismo', models.BooleanField(default=False)),
                ('etilismo', models.BooleanField(default=False)),
                ('profissao_relevante', models.TextField(blank=True, help_text='Aspectos da profissão que impactam a queixa')),
                ('peso', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('altura', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('pressao_arterial', models.CharField(blank=True, help_text='Ex: 120/80', max_length=20)),
                ('frequencia_cardiaca', models.PositiveIntegerField(blank=True, null=True)),
                ('objetivo_paciente', models.TextField(blank=True, help_text='O que o paciente espera do tratamento?')),
                ('observacoes', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('paciente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='anamnese', to='pacientes.paciente')),
            ],
            options={
                'verbose_name': 'Anamnese',
                'verbose_name_plural': 'Anamneses',
            },
        ),
        migrations.CreateModel(
            name='SessaoFisioterapia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('numero_sessao', models.PositiveIntegerField()),
                ('queixa_sessao', models.TextField(blank=True, help_text='Como o paciente chegou hoje?')),
                ('procedimentos', models.TextField(help_text='O que foi realizado na sessão')),
                ('evolucao', models.TextField(blank=True, help_text='Progresso observado')),
                ('intensidade_dor_atual', models.IntegerField(choices=[(0, '0 — Sem dor'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5 — Dor moderada'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10 — Pior dor possível')], default=0)),
                ('proxima_sessao', models.DateField(blank=True, null=True)),
                ('observacoes', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('fisioterapeuta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessoes', to=settings.AUTH_USER_MODEL)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessoes', to='pacientes.paciente')),
            ],
            options={
                'verbose_name': 'Sessão',
                'verbose_name_plural': 'Sessões',
                'ordering': ['-data'],
            },
        ),
    ]
