# Generated by Django 6.0.5 on 2026-05-27 14:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patologia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('descricao', models.TextField()),
                ('foto', models.ImageField(blank=True, null=True, upload_to='patologias/')),
                ('causas', models.TextField(blank=True)),
                ('sintomas', models.TextField(blank=True)),
                ('tratamento', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Patologia',
                'verbose_name_plural': 'Patologias',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='SintomaPatologia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=200)),
                ('patologia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sintomas_relacionados', to='patologias.patologia')),
            ],
        ),
    ]
