# Generated by Django 6.0.5 on 2026-05-27 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercicios', '0001_initial'),
        ('patologias', '0001_initial'),
        ('testes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patologia',
            name='exercicios_relacionados',
            field=models.ManyToManyField(blank=True, related_name='patologias', to='exercicios.exercicio'),
        ),
        migrations.AddField(
            model_name='patologia',
            name='testes_relacionados',
            field=models.ManyToManyField(blank=True, related_name='patologias', to='testes.teste'),
        ),
    ]
