# Generated by Django 6.0.5 on 2026-05-28 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patologias', '0002_patologia_exercicios_relacionados_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sintomapatologia',
            options={'verbose_name': 'Sintoma', 'verbose_name_plural': 'Sintomas'},
        ),
        migrations.RemoveField(
            model_name='patologia',
            name='sintomas',
        ),
        migrations.AddField(
            model_name='patologia',
            name='regiao',
            field=models.CharField(choices=[('ombro', 'Ombro'), ('joelho', 'Joelho'), ('quadril', 'Quadril'), ('coluna', 'Coluna'), ('cotovelo', 'Cotovelo'), ('punho', 'Punho'), ('tornozelo', 'Tornozelo'), ('outros', 'Outros')], default='outros', max_length=20),
            preserve_default=False,
        ),
    ]
