# Generated by Django 6.0.5 on 2026-07-09 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patologias', '0003_alter_sintomapatologia_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patologia',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='fisioapp/patologias/'),
        ),
    ]
