# Generated by Django 6.0.5 on 2026-05-27 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exercicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('descricao', models.TextField()),
                ('como_realizar', models.TextField()),
                ('foto', models.ImageField(blank=True, null=True, upload_to='exercicios/')),
                ('nivel', models.CharField(choices=[('iniciante', 'Iniciante'), ('intermediario', 'Intermediário'), ('avancado', 'Avançado')], max_length=20)),
                ('categoria', models.CharField(choices=[('fortalecimento', 'Fortalecimento'), ('alongamento', 'Alongamento'), ('propriocepcao', 'Propriocepção'), ('mobilidade', 'Mobilidade'), ('aerobico', 'Aeróbico')], max_length=20)),
                ('series', models.PositiveIntegerField(default=3)),
                ('repeticoes', models.CharField(default='10-15', help_text='Ex: 10-15 ou 30 segundos', max_length=50)),
                ('musculo_alvo', models.CharField(max_length=200)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Exercício',
                'verbose_name_plural': 'Exercícios',
                'ordering': ['nome'],
            },
        ),
    ]
