# Generated by Django 6.0.5 on 2026-07-09 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercicios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercicio',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='fisioapp/exercicios/'),
        ),
    ]
