# Generated by Django 6.0.5 on 2026-06-02 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articulacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('nome_cientifico', models.CharField(blank=True, max_length=200)),
                ('regiao', models.CharField(choices=[('cabeca_pescoco', 'Cabeça e Pescoço'), ('ombro', 'Ombro'), ('braco', 'Braço'), ('cotovelo', 'Cotovelo'), ('antebraco', 'Antebraço'), ('punho_mao', 'Punho e Mão'), ('coluna_cervical', 'Coluna Cervical'), ('coluna_toracica', 'Coluna Torácica'), ('coluna_lombar', 'Coluna Lombar'), ('quadril', 'Quadril'), ('coxa', 'Coxa'), ('joelho', 'Joelho'), ('perna', 'Perna'), ('tornozelo_pe', 'Tornozelo e Pé')], max_length=30)),
                ('descricao', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='anatomia/articulacoes/')),
                ('tipo', models.CharField(blank=True, choices=[('sinovial', 'Sinovial'), ('cartilaginosa', 'Cartilaginosa'), ('fibrosa', 'Fibrosa')], max_length=20)),
                ('ossos_envolvidos', models.CharField(blank=True, help_text='Ex: fêmur, tíbia, patela', max_length=300)),
                ('movimentos_possiveis', models.TextField(blank=True, help_text='Ex: flexão, extensão, rotação')),
                ('estruturas_estabilizadoras', models.TextField(blank=True, help_text='Ligamentos e músculos que estabilizam')),
            ],
            options={
                'verbose_name': 'Articulação',
                'verbose_name_plural': 'Articulações',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Ligamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('nome_cientifico', models.CharField(blank=True, max_length=200)),
                ('regiao', models.CharField(choices=[('cabeca_pescoco', 'Cabeça e Pescoço'), ('ombro', 'Ombro'), ('braco', 'Braço'), ('cotovelo', 'Cotovelo'), ('antebraco', 'Antebraço'), ('punho_mao', 'Punho e Mão'), ('coluna_cervical', 'Coluna Cervical'), ('coluna_toracica', 'Coluna Torácica'), ('coluna_lombar', 'Coluna Lombar'), ('quadril', 'Quadril'), ('coxa', 'Coxa'), ('joelho', 'Joelho'), ('perna', 'Perna'), ('tornozelo_pe', 'Tornozelo e Pé')], max_length=30)),
                ('descricao', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='anatomia/ligamentos/')),
                ('articulacao', models.CharField(blank=True, help_text='Articulação que estabiliza', max_length=200)),
                ('funcao', models.TextField(blank=True, help_text='Como estabiliza a articulação')),
                ('lesao_comum', models.CharField(blank=True, help_text='Ex: entorse, ruptura', max_length=200)),
            ],
            options={
                'verbose_name': 'Ligamento',
                'verbose_name_plural': 'Ligamentos',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Musculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('nome_cientifico', models.CharField(blank=True, max_length=200)),
                ('regiao', models.CharField(choices=[('cabeca_pescoco', 'Cabeça e Pescoço'), ('ombro', 'Ombro'), ('braco', 'Braço'), ('cotovelo', 'Cotovelo'), ('antebraco', 'Antebraço'), ('punho_mao', 'Punho e Mão'), ('coluna_cervical', 'Coluna Cervical'), ('coluna_toracica', 'Coluna Torácica'), ('coluna_lombar', 'Coluna Lombar'), ('quadril', 'Quadril'), ('coxa', 'Coxa'), ('joelho', 'Joelho'), ('perna', 'Perna'), ('tornozelo_pe', 'Tornozelo e Pé')], max_length=30)),
                ('descricao', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='anatomia/musculos/')),
                ('origem', models.TextField(help_text='Origem do músculo')),
                ('insercao', models.TextField(help_text='Onde o músculo termina')),
                ('funcao', models.TextField(help_text='Qual movimento ele realiza')),
                ('inervacao', models.CharField(blank=True, help_text='Nervo responsável', max_length=200)),
            ],
            options={
                'verbose_name': 'Músculo',
                'verbose_name_plural': 'Músculos',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Osso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('nome_cientifico', models.CharField(blank=True, max_length=200)),
                ('regiao', models.CharField(choices=[('cabeca_pescoco', 'Cabeça e Pescoço'), ('ombro', 'Ombro'), ('braco', 'Braço'), ('cotovelo', 'Cotovelo'), ('antebraco', 'Antebraço'), ('punho_mao', 'Punho e Mão'), ('coluna_cervical', 'Coluna Cervical'), ('coluna_toracica', 'Coluna Torácica'), ('coluna_lombar', 'Coluna Lombar'), ('quadril', 'Quadril'), ('coxa', 'Coxa'), ('joelho', 'Joelho'), ('perna', 'Perna'), ('tornozelo_pe', 'Tornozelo e Pé')], max_length=30)),
                ('descricao', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='anatomia/ossos/')),
                ('tipo', models.CharField(blank=True, choices=[('longo', 'Longo'), ('curto', 'Curto'), ('plano', 'Plano'), ('irregular', 'Irregular'), ('sesamoide', 'Sesamoide')], max_length=20)),
                ('funcao', models.TextField(blank=True)),
                ('articulacoes_envolvidas', models.CharField(blank=True, max_length=300)),
            ],
            options={
                'verbose_name': 'Osso',
                'verbose_name_plural': 'Ossos',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Tendao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('nome_cientifico', models.CharField(blank=True, max_length=200)),
                ('regiao', models.CharField(choices=[('cabeca_pescoco', 'Cabeça e Pescoço'), ('ombro', 'Ombro'), ('braco', 'Braço'), ('cotovelo', 'Cotovelo'), ('antebraco', 'Antebraço'), ('punho_mao', 'Punho e Mão'), ('coluna_cervical', 'Coluna Cervical'), ('coluna_toracica', 'Coluna Torácica'), ('coluna_lombar', 'Coluna Lombar'), ('quadril', 'Quadril'), ('coxa', 'Coxa'), ('joelho', 'Joelho'), ('perna', 'Perna'), ('tornozelo_pe', 'Tornozelo e Pé')], max_length=30)),
                ('descricao', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='anatomia/tendoes/')),
                ('musculo_associado', models.CharField(blank=True, help_text='Músculo que ele conecta', max_length=200)),
                ('osso_associado', models.CharField(blank=True, help_text='Osso onde se insere', max_length=200)),
                ('funcao', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Tendão',
                'verbose_name_plural': 'Tendões',
                'ordering': ['nome'],
            },
        ),
    ]
