# Generated by Django 6.0.5 on 2026-07-09 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anatomia', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulacao',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='fisioapp/anatomia/articulacoes/'),
        ),
        migrations.AlterField(
            model_name='ligamento',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='fisioapp/anatomia/ligamentos/'),
        ),
        migrations.AlterField(
            model_name='musculo',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='fisioapp/anatomia/musculos/'),
        ),
        migrations.AlterField(
            model_name='osso',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='fisioapp/anatomia/ossos/'),
        ),
        migrations.AlterField(
            model_name='tendao',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='fisioapp/anatomia/tendoes/'),
        ),
    ]
